### ISSUE TITLE
E-mail validation not catching

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/govuk-casa#14]
I've not done a full check but for example the following will pass the validation

```
valid@domain.co.
valid@domain.co,
valid@domain.co!
```

I assume the regex used to do this probably needs a few more edge cases around it and updating.

**Comment by lhokktyn** [comment]
Thanks for catching this @htmlandbacon, I'll take a look into it.

**Comment by htmlandbacon** [comment]
happy to do a PR for something like https://www.npmjs.com/package/email-validator?

**Comment by lhokktyn** [comment]
Resolved in 28cd3005a80f53b662f1806fdc7c02365190a668
