### ISSUE TITLE
Fieldsets are allowed to omit <legend> tags

### ISSUE THREAD

**Issue by colinrotherham** [dwp/govuk-casa#3]
We've noticed when `labelledBy` is configured, fieldsets drop their legend tag. This is required for screen readers and is used to link questions (the legend) with their answers (radios/checkboxes).

Instead, the Design System uses `isPageHeading` and `classes` on the radio/checkbox legend so it can be configured to appear as a larger heading or accessibly hidden instead.

For example, see here: https://github.com/dwp/govuk-casa/blob/a14152373ee467925b07c9989768c22f52629667/app/views/casa/macros/form.njk#L162

We've noticed this used by accident on one of our projects using `checkboxArrayGroup()`.

Additionally, the inner groups aren't described by errors on the wrapping group. Possibly related to https://github.com/dwp/govuk-casa/issues/2

**Comment by lhokktyn** [comment]
Thanks Colin. As this relates to a deprecated macro, the "fix" in this case will be to refactor for using the new [`govukCheckboxes()`](https://design-system.service.gov.uk/components/checkboxes/) or [`casaGovukCheckboxes()`](https://github.com/dwp/govuk-casa/tree/master/app/views/casa/components/checkboxes) macros which should take care of the correct aria labelling for you, as well as giving you more control over the legend.

**Comment by lhokktyn** [comment]
Older v1 macros and CSS have now been removed so the above no longer applies

ref: 40a419a1a3bf744ea03537951f3f8da5517b57ef
