### ISSUE TITLE
Error summary link hrefs should focus form element

### ISSUE THREAD

**Issue by colinrotherham** [dwp/govuk-casa#5]
The GOV.UK Design System recently added better examples for how the summary links integrate with form fields that have errors.

e.g. https://design-system.service.gov.uk/components/error-summary/linking/index.html

But we've found:

**In CASA**
The error summary href incorrectly links to the error `span[govuk-error-message]` element

**In the Design System**
The error summary href correctly links to the `input` field

![error summary link](https://user-images.githubusercontent.com/415517/51911767-8d26b180-23ca-11e9-8b09-93645a059446.png)

If we fix this in CASA, thanks to the recent GOV.UK Frontend 2.4 `ErrorSummary` component, it'll handle all the focus/scroll behaviour for screen readers and other assistive software.

Read more about it here:
https://github.com/alphagov/govuk-frontend/pull/1056

**Comment by lhokktyn** [comment]
This is now fixed and will make its way into the next release.
