### ISSUE TITLE
Make body-parser field/size limits configurable 

### ISSUE THREAD

**Issue by danboscaro** [dwp/govuk-casa#60]
# Summary
Hi @lhokktyn  - we are looking to implement the MoJ version of the "add-another" pattern in our service where we have a maximum of 5 "things" and each thing has 5 fields. https://design-patterns.service.justice.gov.uk/components/add-another/ 

When the user maxes out all the things this tips the field count over the hardcoded 25 parameter limit with the 5x5 fields and the hidden csrf etc
https://github.com/dwp/govuk-casa/blob/1da97cea6a69402ada77bf1fde88e7412b83c68f/src/middleware/body-parser.js#L26-L27

## Proposed solution
Make the body-parser options configurable when initialising the casa application and have them default to their current values if theyre not provided

## Benefits
Greater flexibility for implementing alternate patterns

**Comment by danboscaro** [comment]
I think a global config would be sufficient like it is now, the majority of use cases will be submitting pages with the parameter count well under the limit at the moment which doesnt pose an issue

If a ridiculously high limit is set which would impact on performance/security/maintainability you would hope they would reconsider the design of the page they were building

For our (edge like) case we are only looking to increase the limit by a few fields, and the rest of our pages would still have a limit very similar to it is now that is being highly under utilised

**Comment by lhokktyn** [comment]
An first solution has been pushed to `main`.

**Comment by lhokktyn** [comment]
Feature now available in `8.10.0` 🎉
