### ISSUE TITLE
Optimise implementation of Nunjucks

### ISSUE THREAD

**Issue by lhokktyn** [dwp/govuk-casa#8]
Currently CASA generates a new Nunjucks environment for each and every response, and stores it at `res.nunjucksEnvironment`.

The main reason for this is so we can attach a pre-configured translation function to the global scope of that environment. This function is pre-configured with the current response session's language. We can't attach a pre-configured translation function top the global Nunjucks environment because every session will have a different language, potentially.

The main advantage to this approach is that we can call `t(...)` in any template, or macro, without having to specify the language (e.g. `t('translate me', 'en')`). The main downside to this approach is the additional overhead in terms of memory usage (roughly 55-65% additional memory usage).

@colinrotherham has put together a sample app that instead uses the global Nunjucks environment, and asks the template author to inject the locale where necessary in all function and macro calls. He's kindly put together a sample app to demo this: https://github.com/colinrotherham/express-i18n

The main advantage to that approach is efficiency and explicitness of function calls, and the main downside is the need to pass variables (in this case a `ctx` context var) through to every function/macro that needs it (or if ones of that function/macro's dependencies needs it).

So at a high level the decision is one of **convenience** _vs_ **performance**

Interested in gathering peoples thoughts on the pros and cons of each approach, or suggestions for alternatives.

**Comment by colinrotherham** [comment]
@lhokktyn I did some research, and other i18n middleware packages actually use a local (e.g. `res.locals.t = function`) rather than a Nunjucks global.

Pushed up a third iteration:
https://github.com/colinrotherham/express-i18n/commit/90d419e06a2e8c8c3764825044d12bf7892791b1

We can now use the `t()` function without a context param:

```js
{{ example({
  name: 'James Gauld',
  hello: t('greeting.hello'),
  message: t('greeting.message')
}) }}
```

**Pros:** No globals, no race conditions
**Cons:** Can't access `res.locals` inside macros (again)

**Comment by colinrotherham** [comment]
@lhokktyn Even better, we can enable context (e.g. `t()` function) inside macros too:
https://github.com/colinrotherham/express-i18n/commit/e60b8213aade55af9ea5b80048b10a60e0ddc9a1

Thanks to:

```
{% from "example/macro.njk" import example with context %}
```

See `with context` after the import.

**Comment by lhokktyn** [comment]
This is now featured in version 4, using the `with context` solution outlined above. Thanks again for this great improvement @colinrotherham :)
